/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Clases.Cl_Conectar;
import Clases.Cl_Persona;
import Clases.Cl_Varios;
import Forms.frm_reg_empleado;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import casa_biblia.frm_menu;

/**
 *
 * @author CONTABILIDAD 02
 */
public class frm_ver_empleados extends javax.swing.JInternalFrame {

    Cl_Varios ven = new Cl_Varios();
    Cl_Conectar con = new Cl_Conectar();
    Cl_Persona per = new Cl_Persona();
    public static String ventana = "empleado";
    Integer i;
    String valor;
    DefaultTableModel mostrar;

    /**
     * Creates new form frm_ver_empleado
     */
    public frm_ver_empleados() {
        initComponents();
        String query = "select a.nombre, e.dni, e.nombres, e.ape_pat, e.ape_mat, e.direccion, e.telefono, e.estado from empleados as e inner join almacenes as a on e.almacen = a.id_almacen and e.empresa =  a.empresa order by a.nombre, e.ape_pat asc, e.ape_mat asc";
        ver_empleado(query);
    }

    private void ver_empleado(String query) {
        try {
            mostrar = new DefaultTableModel() {
                @Override
                public boolean isCellEditable(int fila, int columna) {
                    return false;
                }
            };
            Statement st = con.conexion();
            ResultSet rs = con.consulta(st, query);
            mostrar.addColumn("Tienda");
            mostrar.addColumn("DNI");
            mostrar.addColumn("Nombre");
            mostrar.addColumn("Direccion");
            mostrar.addColumn("Telefono");
            mostrar.addColumn("Estado");

            //Creando las filas para el JTable
            while (rs.next()) {
                Object[] fila = new Object[6];
                fila[0] = rs.getString("nombre");
                fila[1] = rs.getString("dni");
                fila[2] = rs.getString("ape_pat") + " " + rs.getString("ape_mat") + " " + rs.getString("nombres");
                fila[3] = rs.getString("direccion");
                fila[4] = rs.getString("telefono");
                String estado = rs.getString("estado");;
                if (estado.equals("1")) {
                    fila[5] = "ACTIVO";
                } else {
                    fila[5] = "-";
                }

                mostrar.addRow(fila);
            }
            con.cerrar(st);
            con.cerrar(rs);
            t_empleado.setModel(mostrar);
            t_empleado.getColumnModel().getColumn(0).setPreferredWidth(30);
            t_empleado.getColumnModel().getColumn(1).setPreferredWidth(30);
            t_empleado.getColumnModel().getColumn(2).setPreferredWidth(200);
            t_empleado.getColumnModel().getColumn(3).setPreferredWidth(190);
            t_empleado.getColumnModel().getColumn(4).setPreferredWidth(50);
            t_empleado.getColumnModel().getColumn(5).setPreferredWidth(30);
            ven.centrar_celda(t_empleado, 0);
            ven.centrar_celda(t_empleado, 1);
            ven.centrar_celda(t_empleado, 4);
            ven.centrar_celda(t_empleado, 5);
            mostrar.fireTableDataChanged();
        } catch (SQLException e) {
            System.out.print(e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_bus = new javax.swing.JTextField();
        btn_reg = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_empleado = new javax.swing.JTable();
        btn_clo = new javax.swing.JButton();
        btn_ret = new javax.swing.JButton();
        btn_mod = new javax.swing.JButton();
        btn_act = new javax.swing.JButton();
        cbx_tipo = new javax.swing.JComboBox();

        setTitle("Ver Empleado");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/find.png"))); // NOI18N
        jLabel1.setText("Buscar");

        txt_bus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_busKeyPressed(evt);
            }
        });

        btn_reg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/application_add.png"))); // NOI18N
        btn_reg.setText("Registrar");
        btn_reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regActionPerformed(evt);
            }
        });

        t_empleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"46993209", "LUIS ENRIQUE OYANGUREN GIRON", "URB. GARATEA 16-4", "947396729", "ACTIVO"},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "DNI", "NOMBRES Y APELLIDOS", "DIRECCION", "TELEFONO", "ESTADO"
            }
        ));
        t_empleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_empleadoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                t_empleadoMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(t_empleado);
        if (t_empleado.getColumnModel().getColumnCount() > 0) {
            t_empleado.getColumnModel().getColumn(0).setPreferredWidth(30);
            t_empleado.getColumnModel().getColumn(1).setPreferredWidth(200);
            t_empleado.getColumnModel().getColumn(2).setPreferredWidth(190);
            t_empleado.getColumnModel().getColumn(3).setPreferredWidth(50);
            t_empleado.getColumnModel().getColumn(4).setPreferredWidth(30);
        }

        btn_clo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/cancel.png"))); // NOI18N
        btn_clo.setText("Cerrar");
        btn_clo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cloActionPerformed(evt);
            }
        });

        btn_ret.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/asterisk_orange.png"))); // NOI18N
        btn_ret.setText("Retirar");
        btn_ret.setEnabled(false);
        btn_ret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_retActionPerformed(evt);
            }
        });

        btn_mod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/application_edit.png"))); // NOI18N
        btn_mod.setText("Modificar");
        btn_mod.setEnabled(false);
        btn_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modActionPerformed(evt);
            }
        });

        btn_act.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/asterisk_orange.png"))); // NOI18N
        btn_act.setText("Re-Ingresar");
        btn_act.setEnabled(false);
        btn_act.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actActionPerformed(evt);
            }
        });

        cbx_tipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DNI", "Nombre" }));
        cbx_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_tipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 885, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_ret)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_act)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_clo))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_bus, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbx_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_reg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_mod)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btn_reg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_bus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ret, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_clo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_act, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cloActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_cloActionPerformed

    private void btn_regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regActionPerformed
        frm_reg_empleado empleado = new frm_reg_empleado();
        frm_reg_empleado.accion = "registrar";
        ven.llamar_ventana(empleado);
        this.dispose();
    }//GEN-LAST:event_btn_regActionPerformed

    private void t_empleadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_empleadoMousePressed

    }//GEN-LAST:event_t_empleadoMousePressed

    private void btn_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modActionPerformed
        if (frm_menu.usu.getPem_emp().equals("1")) {
            frm_reg_empleado empleado = new frm_reg_empleado();
            frm_reg_empleado.accion = "modificar";
            per.setNro_doc(t_empleado.getValueAt(i, 0).toString());
            try {
                Statement st = con.conexion();
                String query = "select * empleado where dni = '" + per.getNro_doc() + "' ";
                ResultSet rs = con.consulta(st, query);
                if (rs.next()) {
                    empleado.txt_ndoc.setText(rs.getString("dni"));
                    empleado.txt_nom.setText(rs.getString("nombre"));
                    empleado.txt_ape_pat.setText(rs.getString("ape_pat"));
                    empleado.txt_ape_mat.setText(rs.getString("ape_mat"));
                    empleado.txt_dir.setText(rs.getString("direccion"));
                    empleado.txt_tel.setText(rs.getString("telefono"));
                    empleado.txt_ndoc.setEditable(false);
                    empleado.txt_nom.setEnabled(true);
                    empleado.txt_ape_pat.setEnabled(true);
                    empleado.txt_ape_mat.setEnabled(true);
                    empleado.txt_dir.setEnabled(true);
                    empleado.txt_tel.setEnabled(true);
                    empleado.txt_jor.setText(ven.formato_numero(rs.getDouble("jornal")));
                    empleado.txt_jor.setEnabled(true);
                    empleado.txt_nom.requestFocus();
                    ven.llamar_ventana(empleado);
                    this.dispose();
                }
            } catch (SQLException ex) {
                System.out.print(ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ud. No tiene permisos");
        }
    }//GEN-LAST:event_btn_modActionPerformed

    private void btn_retActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_retActionPerformed
        if (frm_menu.usu.getPem_emp().equals("1")) {
//retirar empleado
            per.setNro_doc(t_empleado.getValueAt(i, 0).toString());
            Statement st = con.conexion();
            String retira = "update empleado set estado = '0' where dni = '" + per.getNro_doc() + "'";
            con.actualiza(st, retira);
            con.cerrar(st);
            String query = "select dni, nombres, ape_pat, ape_mat, direccion, telefono, estado from empleados order by ape_pat asc, ape_mat asc";
            ver_empleado(query);
        } else {
            JOptionPane.showMessageDialog(null, "Ud. No tiene permisos");
        }
    }//GEN-LAST:event_btn_retActionPerformed

    private void txt_busKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_busKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String buscar = txt_bus.getText();
            String query = "select dni, nombres, ape_pat, ape_mat, direccion, telefono, estado from empleados where dni = '" + buscar + "' or nombres like '%" + buscar + "%' "
                    + "or ape_pat like '%" + buscar + "%' or ape_mat like '%" + buscar + "%' order by ape_pat asc, ape_mat asc";
            ver_empleado(query);
        }
    }//GEN-LAST:event_txt_busKeyPressed

    private void btn_actActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actActionPerformed
        if (frm_menu.usu.getPem_emp().equals("1")) {
            //reingresa al trabajador
            per.setNro_doc(t_empleado.getValueAt(i, 0).toString());
            Statement st = con.conexion();
            String ingresa = "update empleados set estado = '1' where dni = '" + per.getNro_doc() + "'";
            con.actualiza(st, ingresa);
            con.cerrar(st);
            String query = "select dni, nombres, ape_pat, ape_mat, direccion, telefono, estado from empleados order by ape_pat asc, ape_mat asc";
            ver_empleado(query);
        } else {
            JOptionPane.showMessageDialog(null, "Ud. No tiene permisos");
        }
    }//GEN-LAST:event_btn_actActionPerformed

    private void cbx_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_tipoActionPerformed
        txt_bus.setText("");
        txt_bus.requestFocus();
    }//GEN-LAST:event_cbx_tipoActionPerformed

    private void t_empleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_empleadoMouseClicked
        i = t_empleado.getSelectedRow();
        btn_mod.setEnabled(true);

        String estado = t_empleado.getValueAt(i, 4).toString();
        if (estado.equals("-")) {
            btn_act.setEnabled(true);
            btn_ret.setEnabled(false);
        } else {
            btn_act.setEnabled(false);
            btn_ret.setEnabled(true);
        }
    }//GEN-LAST:event_t_empleadoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_act;
    private javax.swing.JButton btn_clo;
    private javax.swing.JButton btn_mod;
    private javax.swing.JButton btn_reg;
    private javax.swing.JButton btn_ret;
    private javax.swing.JComboBox cbx_tipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable t_empleado;
    private javax.swing.JTextField txt_bus;
    // End of variables declaration//GEN-END:variables
}
