/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Clases.Cl_Conectar;
import Clases.Cl_Persona;
import Clases.Cl_Varios;
import Forms.frm_reg_cliente;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pc
 */
public class frm_ver_clientes extends javax.swing.JInternalFrame {

    Cl_Varios ven = new Cl_Varios();
    Cl_Conectar con = new Cl_Conectar();
    Cl_Persona cli = new Cl_Persona();
    public static String origen = "";
    Integer i;
    DefaultTableModel mostrar;

    /**
     * Creates new form frm_cliente
     */
    public frm_ver_clientes() {
        initComponents();
        String query = "select id_cliente, nro_documento, nombre, telefono from clientes order by nombre asc";
        ver_cliente(query);
    }

    private void ver_cliente(String query) {
        try {
            mostrar = new DefaultTableModel() {
                @Override
                public boolean isCellEditable(int fila, int columna) {
                    return false;
                }
            };
            Statement st = con.conexion();
            ResultSet rs = con.consulta(st, query);

            mostrar.addColumn("Cod.");
            mostrar.addColumn("Nro Doc.");
            mostrar.addColumn("Nombre o Razon Social");
            mostrar.addColumn("Telefono");

            //Creando las filas para el JTable
            while (rs.next()) {
                Object[] fila = new Object[4];
                fila[0] = rs.getObject("id_cliente");
                fila[1] = rs.getString("nro_documento").toUpperCase().trim();
                fila[2] = rs.getObject("nombre");
                fila[3] = rs.getObject("telefono");
                mostrar.addRow(fila);
            }
            con.cerrar(st);
            con.cerrar(rs);
            t_clientes.setModel(mostrar);
            t_clientes.getColumnModel().getColumn(0).setPreferredWidth(50);
            t_clientes.getColumnModel().getColumn(1).setPreferredWidth(50);
            t_clientes.getColumnModel().getColumn(2).setPreferredWidth(280);
            t_clientes.getColumnModel().getColumn(3).setPreferredWidth(50);
            ven.centrar_celda(t_clientes, 0);
            ven.centrar_celda(t_clientes, 1);
            ven.centrar_celda(t_clientes, 3);
            mostrar.fireTableDataChanged();
        } catch (SQLException e) {
            System.out.print(e);
            JOptionPane.showMessageDialog(null, e.getLocalizedMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_bus = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btn_mod = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_clientes = new javax.swing.JTable();
        btn_cerrar = new javax.swing.JButton();

        setTitle("Ver Clientes");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/find.png"))); // NOI18N
        jLabel1.setText("Buscar:");

        txt_bus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_busKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_busKeyTyped(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/application_add.png"))); // NOI18N
        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btn_mod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/application_edit.png"))); // NOI18N
        btn_mod.setText("Modifcar");
        btn_mod.setEnabled(false);
        btn_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modActionPerformed(evt);
            }
        });

        t_clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"46993209", "LUIS ENRIQUE OYANGUREN GIRON", "947396729", "Normal"},
                {"10469932091", "LEOG SYSTEMS ", "947396729", "Normal"},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nro. Doc", "Nombre o Razon Social", "Telefono", "Estado"
            }
        ));
        t_clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_clientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(t_clientes);
        if (t_clientes.getColumnModel().getColumnCount() > 0) {
            t_clientes.getColumnModel().getColumn(0).setPreferredWidth(50);
            t_clientes.getColumnModel().getColumn(1).setPreferredWidth(200);
            t_clientes.getColumnModel().getColumn(2).setPreferredWidth(50);
            t_clientes.getColumnModel().getColumn(3).setPreferredWidth(20);
        }

        btn_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/cancel.png"))); // NOI18N
        btn_cerrar.setText("Cerrar");
        btn_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 747, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_bus, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_mod))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_cerrar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_bus, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_cerrarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        frm_reg_cliente cliente = new Forms.frm_reg_cliente();
        cliente.accion = "registrar";
        cliente.origen = "cliente";
        ven.llamar_ventana(cliente);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_busKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_busKeyTyped

    }//GEN-LAST:event_txt_busKeyTyped

    private void txt_busKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_busKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String buscar = txt_bus.getText();
            String query = "select id_cliente, nro_documento, nombre, telefono from clientes where nombre like '%" + buscar + "%' or nro_documento like '%" + buscar + "%' order by nombre asc limit 10";
            ver_cliente(query);
        }
    }//GEN-LAST:event_txt_busKeyPressed

    private void btn_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modActionPerformed
        frm_reg_cliente cliente = new frm_reg_cliente();
        try {
            Statement st = con.conexion();
            String ver_cli = "select * from clientes where id_cliente = '" + cli.getNro_doc() + "'";
            ResultSet rs = con.consulta(st, ver_cli);
            if (rs.next()) {
                cliente.cbx_cli.setEnabled(false);
                cliente.lbl_codigo.setText(rs.getString("id_cliente"));
                cliente.txt_ndoc.setText(rs.getString("nro_documento"));
                cliente.txt_ndoc.setEditable(false);
                cliente.txt_nom.setText(rs.getString("nombre"));
                cliente.txt_nom.setEditable(true);
                cliente.txt_nom.requestFocus();
                cliente.txt_dir.setText(rs.getString("direccion"));
                cliente.txt_dir.setEditable(true);
                cliente.txt_tel.setText(rs.getString("telefono"));
                cliente.txt_tel.setEditable(true);
                cliente.btn_lim.setEnabled(false);
                cliente.btn_reg.setEnabled(true);
                cliente.accion = "modificar";
                ven.llamar_ventana(cliente);
                this.dispose();
            }
        } catch (SQLException ex) {
            System.out.print(ex);
        }
    }//GEN-LAST:event_btn_modActionPerformed

    private void t_clientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_clientesMouseClicked
        i = t_clientes.getSelectedRow();
        btn_mod.setEnabled(true);
        cli.setNro_doc(t_clientes.getValueAt(i, 0).toString());
    }//GEN-LAST:event_t_clientesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cerrar;
    private javax.swing.JButton btn_mod;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable t_clientes;
    private javax.swing.JTextField txt_bus;
    // End of variables declaration//GEN-END:variables
}
