/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Clases.Cl_Conectar;
import Clases.Cl_Varios;
import casa_biblia.frm_menu;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luis-d
 */
public class frm_ver_pedidos_cliente extends javax.swing.JInternalFrame {

    Cl_Conectar con = new Cl_Conectar();
    Cl_Varios ven = new Cl_Varios();
    DefaultTableModel model_pedidos;

    /**
     * Creates new form frm_ver_pedidos_cliente
     */
    public frm_ver_pedidos_cliente() {
        initComponents();
        int tienda = frm_menu.alm.getCodigo();
        String empresa = frm_menu.emp.getRuc();
        String hoy = ven.getFechaActual();
        String query = "select pc.id, pc.anio, pc.fecha_pedido, pc.fecha_cobro, pc.estado, pc.total, pc.cajero, ev.nombres, ev.ape_pat from pedido_cliente as pc inner join empleados as ev on pc.vendedor = ev.dni where (pc.fecha_pedido like '" + hoy + "%' or pc.fecha_cobro like '" + hoy + "%') and pc.tienda = '" + tienda + "' and pc.empresa = '" + empresa + "'";
        System.out.println(query);
        modelo_pedidos(query);
    }

    private void modelo_pedidos(String query) {

        model_pedidos = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int fila, int columna) {
                return false;
            }
        };
        model_pedidos.addColumn("COD");
        model_pedidos.addColumn("AÑO");
        model_pedidos.addColumn("FECHA PED.");
        model_pedidos.addColumn("FECHA COBRO");
        model_pedidos.addColumn("VENDEDOR");
        model_pedidos.addColumn("TOTAL");
        model_pedidos.addColumn("CAJERO");
        model_pedidos.addColumn("ESTADO");
        Object[] fila = new Object[8];
        try {
            Statement st = con.conexion();
            ResultSet rs = con.consulta(st, query);
            while (rs.next()) {
                fila[0] = rs.getInt("id");
                fila[1] = rs.getInt("anio");
                fila[2] = ven.fecha_larga_tabla(rs.getString("fecha_pedido"));
                String fecha_cobro = rs.getString("fecha_cobro");
                String fecha_larga = ven.fecha_larga_tabla(fecha_cobro);
                if (fecha_larga.equals("01/01/2070 00:00:01") || fecha_cobro.equals("2070-01-01 00:00:00")) {
                    fila[3] = "-";
                } else {
                    fila[3] = ven.fecha_larga_tabla(fecha_cobro);
                }
                fila[4] = rs.getString("ev.nombres").charAt(0) + rs.getString("ev.ape_pat");
                fila[5] = ven.formato_numero(rs.getDouble("total"));

                String estado = rs.getString("estado");
                if (estado.equals("0")) {
                    fila[7] = "PENDIENTE";
                    fila[6] = "-";
                } else {
                    fila[7] = "CANCELADO";
                    fila[6] = rs.getString("cajero");
                }
                model_pedidos.addRow(fila);
            }
            con.cerrar(rs);
            con.cerrar(st);
            t_pedidos.setModel(model_pedidos);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getLocalizedMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        t_pedidos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setText("Buscar:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "FECHA", "PEDIDO" }));

        t_pedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(t_pedidos);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/cancel.png"))); // NOI18N
        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 864, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable t_pedidos;
    // End of variables declaration//GEN-END:variables
}
