/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Clases.Cl_Conectar;
import Clases.Cl_Proveedor;
import Clases.Cl_Varios;
import Forms.frm_reg_ingreso;
import Forms.frm_reg_proveedor;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pc
 */
public class frm_ver_proveedor extends javax.swing.JInternalFrame {

    Cl_Varios ven = new Cl_Varios();
    Cl_Conectar con = new Cl_Conectar();
    Cl_Proveedor pro = new Cl_Proveedor();
    public static String ventana = "proveedor";
    DefaultTableModel mostrar;
    Integer i;

    /**
     * Creates new form frm_ver_proveedor
     */
    public frm_ver_proveedor() {
        initComponents();
        String query = "select ruc_proveedor, razon_social, direccion from proveedores order by razon_social asc";
        ver_proveedor(query);
    }

    private void ver_proveedor(String query) {
        try {
            mostrar = new DefaultTableModel() {
                @Override
                public boolean isCellEditable(int fila, int columna) {
                    return false;
                }
            };
            Statement st = con.conexion();
            ResultSet rs = con.consulta(st, query);

            mostrar.addColumn("RUC");
            mostrar.addColumn("Razon Social");
            mostrar.addColumn("Direccion");

            //Creando las filas para el JTable
            while (rs.next()) {
                Object[] fila = new Object[3];
                fila[0] = rs.getString("ruc_proveedor");
                fila[1] = rs.getString("razon_social").toUpperCase();
                fila[2] = rs.getString("direccion");
                mostrar.addRow(fila);
            }
            con.cerrar(st);
            con.cerrar(rs);
            t_proveedor.setModel(mostrar);
            t_proveedor.getColumnModel().getColumn(0).setPreferredWidth(40);
            t_proveedor.getColumnModel().getColumn(1).setPreferredWidth(300);
            t_proveedor.getColumnModel().getColumn(2).setPreferredWidth(150);
            ven.centrar_celda(t_proveedor, 0);
            mostrar.fireTableDataChanged();
        } catch (SQLException e) {
            System.out.print(e);
            JOptionPane.showMessageDialog(null, e.getLocalizedMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_registrar = new javax.swing.JButton();
        btn_mod = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_bus = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_proveedor = new javax.swing.JTable();
        btn_cerrar = new javax.swing.JButton();
        btn_eli = new javax.swing.JButton();

        setTitle("Listar Proveedor");

        btn_registrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/application_add.png"))); // NOI18N
        btn_registrar.setText("Registrar");
        btn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarActionPerformed(evt);
            }
        });

        btn_mod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/application_edit.png"))); // NOI18N
        btn_mod.setText("Modifcar");
        btn_mod.setEnabled(false);
        btn_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/find.png"))); // NOI18N
        jLabel1.setText("Buscar:");

        txt_bus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_busKeyPressed(evt);
            }
        });

        t_proveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"46993209", "LUIS ENRIQUE OYANGUREN GIRON", "947396729", "Normal"},
                {"10469932091", "LEOG SYSTEMS ", "947396729", "Normal"},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "RUC", "Nombre o Razon Social", "Telefono", "Estado"
            }
        ));
        t_proveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_proveedorMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                t_proveedorMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(t_proveedor);
        if (t_proveedor.getColumnModel().getColumnCount() > 0) {
            t_proveedor.getColumnModel().getColumn(0).setPreferredWidth(40);
            t_proveedor.getColumnModel().getColumn(1).setPreferredWidth(200);
            t_proveedor.getColumnModel().getColumn(2).setPreferredWidth(40);
            t_proveedor.getColumnModel().getColumn(3).setPreferredWidth(40);
        }

        btn_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/cancel.png"))); // NOI18N
        btn_cerrar.setText("Cerrar");
        btn_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrarActionPerformed(evt);
            }
        });

        btn_eli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/cross.png"))); // NOI18N
        btn_eli.setText("Eliminar");
        btn_eli.setEnabled(false);
        btn_eli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_bus, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_registrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_mod))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_eli)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_cerrar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_bus, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_eli, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_cerrarActionPerformed

    private void btn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarActionPerformed
        frm_reg_proveedor proveedor = new frm_reg_proveedor();
        proveedor.accion = "registrar";
        ven.llamar_ventana(proveedor);
        this.dispose();
    }//GEN-LAST:event_btn_registrarActionPerformed

    private void txt_busKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_busKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String valor_busqueda = txt_bus.getText();
            String query = "select ruc_proveedor, razon_social, direccion from proveedores where ruc_proveedor like '%" + valor_busqueda + "%' or razon_social like "
                    + "'%" + valor_busqueda + "%' order by razon_social asc";
            ver_proveedor(query);
        }
    }//GEN-LAST:event_txt_busKeyPressed

    private void t_proveedorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_proveedorMousePressed
        i = t_proveedor.getSelectedRow();
        pro.setRuc(t_proveedor.getValueAt(i, 0).toString());
        btn_mod.setEnabled(true);
        btn_eli.setEnabled(true);

    }//GEN-LAST:event_t_proveedorMousePressed

    private void btn_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modActionPerformed
        frm_reg_proveedor prov = new frm_reg_proveedor();
        try {
            String idpro = t_proveedor.getValueAt(i, 0).toString();
            String query = "select * from proveedores where ruc_proeedor = '" + idpro + "'";
            Statement st = con.conexion();
            ResultSet rs = con.consulta(st, query);
            if (rs.next()) {
                prov.txt_ruc.setText(rs.getString("ruc_proeedor"));
                prov.txt_ruc.setEditable(false);
                prov.txt_raz.setText(rs.getString("razon_social"));
                prov.txt_raz.setEditable(true);
                prov.txt_raz.requestFocus();
                prov.txt_dir.setText(rs.getString("direccion"));
                prov.txt_dir.setEditable(true);
                prov.txt_web.setText(rs.getString("web"));
                prov.txt_web.setEditable(true);
                prov.accion = "modificar";
                prov.btn_reg.setEnabled(true);
                ven.llamar_ventana(prov);
                this.dispose();
            }
        } catch (SQLException ex) {
            System.out.print(ex);
            JOptionPane.showMessageDialog(null, ex.getLocalizedMessage());
        }
    }//GEN-LAST:event_btn_modActionPerformed

    private void btn_eliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliActionPerformed
        int confirmado = JOptionPane.showConfirmDialog(
                null,
                "¿Confirma eliminar el Proveedor?");

        if (JOptionPane.OK_OPTION == confirmado) {
            try {
                Statement st = con.conexion();
                String eli_cli = "delete from proveedores where ruc_proveedor = '" + pro.getRuc() + "'";
                con.actualiza(st, eli_cli);
                con.cerrar(st);
                String query = "select ruc_proveedor, razon_social, direccion from proveedores order by razon_social asc";
                ver_proveedor(query);
            } catch (Exception ex) {
                System.out.print(ex.getLocalizedMessage());
                JOptionPane.showMessageDialog(null, "Error al Eliminar!");
                JOptionPane.showMessageDialog(null, ex.getLocalizedMessage());
            }
        } else {
            System.out.print("no hago nada!");
        }
        btn_eli.setEnabled(false);
    }//GEN-LAST:event_btn_eliActionPerformed

    private void t_proveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_proveedorMouseClicked
        if (evt.getClickCount() == 2) {
            if (ventana.equals("compra")) {
                frm_reg_ingreso.txt_ruc.setText(t_proveedor.getValueAt(i, 0).toString());
                frm_reg_ingreso.txt_razon_social.setText(t_proveedor.getValueAt(i, 1).toString());
                ventana = "proveedor";
                this.dispose();
            }
        }
    }//GEN-LAST:event_t_proveedorMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cerrar;
    private javax.swing.JButton btn_eli;
    private javax.swing.JButton btn_mod;
    private javax.swing.JButton btn_registrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable t_proveedor;
    private javax.swing.JTextField txt_bus;
    // End of variables declaration//GEN-END:variables
}
