/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author luis-d
 */
public class frm_ver_imagen_mini extends javax.swing.JInternalFrame {

    /**
     * Creates new form frm_ver_imagen_mini
     */
    public frm_ver_imagen_mini() {
        initComponents();
    }

    public static void cargar_imagen(String imgname) {
        try {
            //cargar imagen 
            ImagenURL Imagen = new ImagenURL();
            //JOptionPane.showMessageDialog(null, "el nombre de imagen es " + imgname);
            //System.out.println(imgname);
            if (imgname == null || "".equals(imgname) || imgname.equals("null")) {
                imgname = "noimage.jpg";
            }
            String url;
            String server = "www.lunasystemsperu.com";
            url = "http://" + server + "/casa_biblia/imagenes/productos/" + imgname;
           // System.out.println(url + "\n");
            Imagen.setlink(url);
            jp_imagen.add(Imagen);
            jp_imagen.repaint();
            //fin de carga
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error al cargar imagen");
            System.out.println(ex);
        }
    }

    public static class ImagenURL extends javax.swing.JPanel {

        String link;

        public ImagenURL() {
            this.setSize(200, 200); //se selecciona el tamaño del panel
        }

        public void paint(Graphics grafico) {
            Dimension height = getSize();
            URL url;
            ImageIcon Img = null;
            try {
                url = new URL(link);
                BufferedImage c = ImageIO.read(url);
                Img = new ImageIcon(c);
                grafico.drawImage(Img.getImage(), 0, 0, height.width, height.height, null);
                setOpaque(false);
                super.paintComponent(grafico);
            } catch (MalformedURLException ex) {
                System.out.print(ex);
                JOptionPane.showMessageDialog(null, "no se puede mostrar la imagen \nerror con " + ex);
            } catch (IOException ex) {
                System.out.print(ex);
                JOptionPane.showMessageDialog(null, "no se puede mostrar la imagen \nerror con " + ex);
            }
//            grafico.drawImage(Img.getImage(), 0, 0, height.width, height.height, null);
//            setOpaque(false);
//            super.paintComponent(grafico);
        }

        public void setlink(String url) {
            link = url;
        }

        public String getlink() {
            return link;
        }
    }

   /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_imagen = new javax.swing.JPanel();

        setClosable(true);
        setTitle("Imagen del Producto");

        javax.swing.GroupLayout jp_imagenLayout = new javax.swing.GroupLayout(jp_imagen);
        jp_imagen.setLayout(jp_imagenLayout);
        jp_imagenLayout.setHorizontalGroup(
            jp_imagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 214, Short.MAX_VALUE)
        );
        jp_imagenLayout.setVerticalGroup(
            jp_imagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 205, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jp_imagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jp_imagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JPanel jp_imagen;
    // End of variables declaration//GEN-END:variables
}
