/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Generales;

import Clases.Cl_Conectar;
import Clases.Cl_Varios;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */
public class frm_rpt_entre_fechas extends javax.swing.JInternalFrame {

    Cl_Conectar con = new Cl_Conectar();
    Cl_Varios ven = new Cl_Varios();
    public static String rpt = "";

    /**
     * Creates new form frm_rpt_fechas
     */
    public frm_rpt_entre_fechas() {
        initComponents();
        txt_fec_ini.setText(ven.fechaformateada(ven.getFechaActual()));
        txt_fec_fin.setText(ven.fechaformateada(ven.getFechaActual()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txt_fec_ini = new javax.swing.JFormattedTextField();
        txt_fec_fin = new javax.swing.JFormattedTextField();

        setTitle("Imprimir Reportes");

        jLabel1.setText("Ingrese Fechas:");

        jLabel2.setText("Fecha Inicio:");

        jLabel3.setText("Fecha Fin:");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/cancel.png"))); // NOI18N
        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        try {
            txt_fec_ini.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_fec_ini.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_fec_ini.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_fec_iniKeyPressed(evt);
            }
        });

        txt_fec_fin.setEditable(false);
        try {
            txt_fec_fin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_fec_fin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_fec_fin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_fec_finKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_fec_ini, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_fec_fin, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                        .addGap(33, 33, 33))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_fec_ini, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_fec_fin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_fec_iniKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_fec_iniKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txt_fec_ini.getText().length() == 10) {
                txt_fec_fin.setEditable(true);
                txt_fec_fin.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_fec_iniKeyPressed

    private void txt_fec_finKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_fec_finKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txt_fec_fin.getText().length() == 10) {
                String fecha_ini = ven.fechabase(txt_fec_ini.getText());
                String fecha_fin = ven.fechabase(txt_fec_fin.getText());

                if (rpt.equals("venta_fec")) {
                    Map<String, Object> parametros = new HashMap<>();
                    parametros.put("fecha_ini", fecha_ini);
                    parametros.put("fecha_fin", fecha_fin);
                    ven.ver_reporte("rpt_ver_ventas_hoy", parametros);
                }

                if (rpt.equals("venta_sunat")) {
                    String fecha = ven.getFechaActual();
                    File miDir = new File(".");
                    try {
                        System.out.println("Directorio actual: " + miDir.getCanonicalPath());
                        Map<String, Object> parametros = new HashMap<>();
                        parametros.put("fecha_ini", fecha_ini);
                        parametros.put("fecha_fin", fecha_fin);
                        String path = miDir.getCanonicalPath();
                        String direccion = path + "\\reports\\subreports\\";
                        parametros.put("SUBREPORT_DIR", direccion);
                        String filename = "rpt_ver_ventas_hoy";
                        ven.ver_reporte(filename, parametros);
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                }

                if (rpt.equals("venta_sunat_rep")) {
                    Map<String, Object> parametros = new HashMap<>();
                    parametros.put("fecha_ini", fecha_ini);
                    parametros.put("fecha_fin", fecha_fin);
                    ven.ver_reporte("rpt_ver_ventas_sunat", parametros);
                }
                
                if (rpt.equals("venta_pro_cant")) {
                    Map<String, Object> parametros = new HashMap<>();
                    parametros.put("fecha_ini", fecha_ini);
                    parametros.put("fecha_fin", fecha_fin);
                    ven.ver_reporte("rpt_ventas_productos_cant", parametros);
                }

                if (rpt.equals("venta_pro_valor")) {
                    Map<String, Object> parametros = new HashMap<>();
                    parametros.put("fecha_ini", fecha_ini);
                    parametros.put("fecha_fin", fecha_fin);
                    ven.ver_reporte("rpt_ventas_productos_valor", parametros);
                }

                if (rpt.equals("venta_cliente")) {
                    Map<String, Object> parametros = new HashMap<>();
                    parametros.put("fecha_ini", fecha_ini);
                    parametros.put("fecha_fin", fecha_fin);
                    ven.ver_reporte("rpt_ventas_clientes", parametros);
                }

                if (rpt.equals("venta_pro_veh")) {
                    Map<String, Object> parametros = new HashMap<>();
                    parametros.put("fecha_ini", fecha_ini);
                    parametros.put("fecha_fin", fecha_fin);
                    ven.ver_reporte("rpt_ventas_vehiculo", parametros);
                }

                if (rpt.equals("gra_productos")) {
                    Map<String, Object> parametros = new HashMap<>();
                    parametros.put("fecha_ini", fecha_ini);
                    parametros.put("fecha_fin", fecha_fin);
                    ven.ver_reporte("gra_ventas_productos_cant", parametros);
                }

                if (rpt.equals("compra_sunat")) {
                    Map<String, Object> parametros = new HashMap<>();
                    parametros.put("fecha_ini", fecha_ini);
                    parametros.put("fecha_fin", fecha_fin);
                    ven.ver_reporte("rpt_ver_compras_sunat", parametros);
                }

                if (rpt.equals("compra_fecha")) {
                    Map<String, Object> parametros = new HashMap<>();
                    parametros.put("fecha_ini", fecha_ini);
                    parametros.put("fecha_fin", fecha_fin);
                    ven.ver_reporte("rpt_ver_compras_fecha", parametros);
                }

                if (rpt.equals("compra_producto")) {
                    Map<String, Object> parametros = new HashMap<>();
                    parametros.put("fecha_ini", fecha_ini);
                    parametros.put("fecha_fin", fecha_fin);
                    ven.ver_reporte("rpt_ver_compras_producto", parametros);
                }

                if (rpt.equals("compra_valor")) {
                    Map<String, Object> parametros = new HashMap<>();
                    parametros.put("fecha_ini", fecha_ini);
                    parametros.put("fecha_fin", fecha_fin);
                    ven.ver_reporte("rpt_ver_compras_valor", parametros);
                }

                if (rpt.equals("compra_proveedor")) {
                    Map<String, Object> parametros = new HashMap<>();
                    parametros.put("fecha_ini", fecha_ini);
                    parametros.put("fecha_fin", fecha_fin);
                    ven.ver_reporte("rpt_ver_compras_proveedor", parametros);
                }

                if (rpt.equals("ver_utilidades")) {
                    Map<String, Object> parametros = new HashMap<>();
                    parametros.put("fecha_ini", fecha_ini);
                    parametros.put("fecha_fin", fecha_fin);
                    ven.ver_reporte("rpt_ver_utilidades", parametros);
                }

                if (rpt.equals("ver_movimientos_dias")) {
                    Map<String, Object> parametros = new HashMap<>();
                    parametros.put("fecha_ini", fecha_ini);
                    parametros.put("fecha_fin", fecha_fin);
                    ven.ver_reporte("rpt_ver_movimiento_dias", parametros);
                }
                JOptionPane.showMessageDialog(null, "Reporte Generado");
                this.dispose();
            }
        }

    }//GEN-LAST:event_txt_fec_finKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JFormattedTextField txt_fec_fin;
    private javax.swing.JFormattedTextField txt_fec_ini;
    // End of variables declaration//GEN-END:variables
}
