/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Generales;

import Clases.Cl_Varios;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author Administrador
 */
public class frm_rpt_buscar_periodo extends javax.swing.JInternalFrame {

    Cl_Varios ven = new Cl_Varios();
    public static String origen = "";

    /**
     * Creates new form frm_bus_per
     */
    public frm_rpt_buscar_periodo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_per = new javax.swing.JFormattedTextField();
        btn_ace = new javax.swing.JButton();

        setClosable(true);
        setTitle("Buscar por Periodo");

        jLabel1.setText("Ingrese Periodo:");

        try {
            txt_per.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_per.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_per.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_perKeyPressed(evt);
            }
        });

        btn_ace.setText("Aceptar");
        btn_ace.setEnabled(false);
        btn_ace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_per, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addComponent(btn_ace)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_per, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ace, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_perKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_perKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txt_per.getText().length() == 7) {
                btn_ace.setEnabled(true);
                btn_ace.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_perKeyPressed

    private void btn_aceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceActionPerformed
        String periodo = txt_per.getText();
        if (origen.equals("compra")) {
            Map<String, Object> parametros = new HashMap<>();
            parametros.put("periodo", periodo);
            String filename = "rpt_ver_compras";
            ven.ver_reporte(filename, parametros);
        }

        if (origen.equals("compra_pagos")) {
            File miDir = new File(".");
            try {
                System.out.println("Directorio actual: " + miDir.getCanonicalPath());
                Map<String, Object> parametros = new HashMap<>();
                parametros.put("periodo", periodo);
                String path = miDir.getCanonicalPath();
                String direccion = path + "\\reports\\subreports\\";
                parametros.put("SUBREPORT_DIR", direccion);
                String filename = "rpt_compras_detalle";
                ven.ver_reporte(filename, parametros);
            } catch (IOException e) {
                e.printStackTrace();
            }
        }

        this.dispose();
    }//GEN-LAST:event_btn_aceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ace;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JFormattedTextField txt_per;
    // End of variables declaration//GEN-END:variables
}
