/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Generales;

import Clases.Cl_Conectar;
import Clases.Cl_Varios;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CONTABILIDAD 02
 */
public class frm_tipo_cambio extends javax.swing.JInternalFrame {

    Cl_Conectar con = new Cl_Conectar();
    Cl_Varios ven = new Cl_Varios();
    DefaultTableModel mostrar;
    String accion = null;
    //Variables 
    String fecha;
    int moneda;
    Double pvta;
    Double pcom;

    /**
     * Creates new form frm_tipo_cambio
     */
    public frm_tipo_cambio() {
        initComponents();
        txt_fec.setText(ven.fechaformateada(ven.getFechaActual()));
        ver_cambios();
        ver_moneda();
    }

    private void ver_cambios() {
        mostrar = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int fila, int columna) {
                return false;
            }
        };
        mostrar.addColumn("Fecha");
        mostrar.addColumn("Moneda");
        mostrar.addColumn("P. Vta.");
        mostrar.addColumn("P. Com.");
        try {
            Statement st = con.conexion();
            String ver_cam = "select tc.fecha, m.nombre, tc.compra, tc.venta from tipo_cambio as tc inner join moneda as m on tc.id_moneda = "
                    + "m.id_moneda where month(tc.fecha) = month(current_date()) and  year(tc.fecha) = year(current_date()) order by tc.fecha desc";
            ResultSet rs = con.consulta(st, ver_cam);
            Object fila[] = new Object[4];
            while (rs.next()) {
                fila[0] = ven.fechaformateada(rs.getString("fecha"));
                fila[1] = rs.getString("nombre").toUpperCase();
                fila[2] = ven.formato_tc(rs.getDouble("venta"));
                fila[3] = ven.formato_tc(rs.getDouble("compra"));
                mostrar.addRow(fila);
            }
            con.cerrar(rs);
            con.cerrar(st);

        } catch (SQLException e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, e.getLocalizedMessage());
        }
        t_cambio.setModel(mostrar);
        t_cambio.getColumnModel().getColumn(0).setPreferredWidth(80);
        t_cambio.getColumnModel().getColumn(1).setPreferredWidth(120);
        t_cambio.getColumnModel().getColumn(2).setPreferredWidth(50);
        t_cambio.getColumnModel().getColumn(3).setPreferredWidth(50);
        ven.centrar_celda(t_cambio, 0);
        ven.derecha_celda(t_cambio, 2);
        ven.derecha_celda(t_cambio, 3);
    }

    private void ver_moneda() {
        ArrayList lista_moneda = new ArrayList();
        try {
            Statement st = con.conexion();
            String query = "select nombre from moneda order by id_moneda asc";
            ResultSet rs = con.consulta(st, query);
            while (rs.next()) {
                lista_moneda.add(rs.getString("nombre"));
            }
            con.cerrar(st);
            con.cerrar(rs);
        } catch (SQLException ex) {
            System.out.print(ex);
            JOptionPane.showMessageDialog(null, ex.getLocalizedMessage());
        }
        for (Object moneda_cbx : lista_moneda) {
            cbx_moneda.addItem(moneda_cbx);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txt_fec = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_ven = new javax.swing.JTextField();
        txt_com = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_cambio = new javax.swing.JTable();
        btn_cer = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        cbx_moneda = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();

        setTitle("Tipo de Cambio");

        jLabel2.setText("Fecha");

        try {
            txt_fec.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_fec.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_fec.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_fecKeyPressed(evt);
            }
        });

        jLabel3.setText("P. Venta:");

        jLabel4.setText("P. Compra:");

        txt_ven.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_ven.setEnabled(false);
        txt_ven.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_venKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_venKeyTyped(evt);
            }
        });

        txt_com.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_com.setEnabled(false);
        txt_com.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_comKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_comKeyTyped(evt);
            }
        });

        t_cambio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(t_cambio);

        btn_cer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/cancel.png"))); // NOI18N
        btn_cer.setText("Cerrar");
        btn_cer.setEnabled(false);
        btn_cer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerActionPerformed(evt);
            }
        });

        btn_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/add.png"))); // NOI18N
        btn_add.setText("Agregar");
        btn_add.setEnabled(false);
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        cbx_moneda.setEnabled(false);
        cbx_moneda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbx_monedaKeyPressed(evt);
            }
        });

        jLabel5.setText("Moneda:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_fec, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbx_moneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txt_ven, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_com, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_cer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_cer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_fec, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbx_moneda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_com, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_ven, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_fecKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_fecKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txt_fec.getText().length() == 10) {
                cbx_moneda.setEnabled(true);
                cbx_moneda.setSelectedIndex(1);
                cbx_moneda.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_fecKeyPressed

    private void txt_venKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_venKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txt_ven.getText().length() > 1) {
                btn_add.setEnabled(true);
                btn_add.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_venKeyPressed

    private void txt_comKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_comKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txt_com.getText().length() > 1) {
                txt_ven.setEnabled(true);
                txt_ven.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_comKeyPressed

    private void llenar() {
        fecha = ven.fechabase(txt_fec.getText());
        moneda = cbx_moneda.getSelectedIndex() + 1;
        pvta = Double.parseDouble(txt_ven.getText());
        pcom = Double.parseDouble(txt_com.getText());
    }

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        llenar();
        if (accion.equals("registrar")) {
            try {
                Statement st = con.conexion();
                String ins_cam = "insert into tipo_cambio Values ('" + fecha + "', '" + pcom + "', '" + pvta + "', '" + moneda + "')";
                System.out.println(ins_cam);
                con.actualiza(st, ins_cam);
                con.cerrar(st);
            } catch (Exception ex) {
                System.out.print(ex);
                JOptionPane.showMessageDialog(null, ex.getLocalizedMessage());
            }
        }

        if (accion.equals("modificar")) {
            try {
                Statement st = con.conexion();
                String upd_cam = "update tipo_cambio set compra = '" + pcom + "', venta = '" + pvta + "' where fecha = '" + fecha + "' and "
                        + "id_moneda = '" + moneda + "'";
                System.out.println(upd_cam);
                con.actualiza(st, upd_cam);
                con.cerrar(st);
            } catch (Exception ex) {
                System.out.print(ex);
                JOptionPane.showMessageDialog(null, ex.getLocalizedMessage());
            }
        }

        ver_cambios();
        accion = null;
        txt_fec.setEnabled(true);
        cbx_moneda.setEnabled(false);
        txt_ven.setEnabled(false);
        txt_com.setEnabled(false);
        txt_ven.setText("");
        txt_com.setText("");
        btn_cer.setEnabled(true);
        txt_fec.requestFocus();
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_cerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerActionPerformed
        accion = null;
        this.dispose();
    }//GEN-LAST:event_btn_cerActionPerformed

    private void cbx_monedaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbx_monedaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!cbx_moneda.getSelectedItem().equals("SOLES")) {
                fecha = ven.fechabase(txt_fec.getText());
                moneda = cbx_moneda.getSelectedIndex() + 1;
                try {
                    Statement st = con.conexion();
                    String comprueba_fecha = "select compra, venta from tipo_cambio where fecha = '" + fecha + "' and id_moneda = '" + moneda + "'";
                    ResultSet rs = con.consulta(st, comprueba_fecha);
                    if (rs.next()) {
                        accion = "modificar";
                        txt_com.setText(ven.formato_tc(rs.getDouble("compra")));
                        txt_com.setEnabled(true);
                        txt_ven.setText(ven.formato_tc(rs.getDouble("venta")));
                        txt_ven.setEnabled(true);
                        txt_com.requestFocus();
                    } else {
                        accion = "registrar";
                        txt_com.setEnabled(true);
                        txt_com.requestFocus();
                    }
                    con.cerrar(rs);
                    con.cerrar(st);
                } catch (Exception e) {
                    System.out.println(e);
                    JOptionPane.showMessageDialog(null, e.getLocalizedMessage());
                }
            } else {
                JOptionPane.showMessageDialog(null, "SELECCIONE OTRA MONEDA");
            }
        }
    }//GEN-LAST:event_cbx_monedaKeyPressed

    private void txt_venKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_venKeyTyped
        char car = evt.getKeyChar();
        if ((car < '0' || car > '9') && car != '.') {
            evt.consume();
        }
    }//GEN-LAST:event_txt_venKeyTyped

    private void txt_comKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_comKeyTyped
        char car = evt.getKeyChar();
        if ((car < '0' || car > '9') && car != '.') {
            evt.consume();
        }
    }//GEN-LAST:event_txt_comKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_cer;
    private javax.swing.JComboBox cbx_moneda;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable t_cambio;
    private javax.swing.JTextField txt_com;
    private javax.swing.JFormattedTextField txt_fec;
    private javax.swing.JTextField txt_ven;
    // End of variables declaration//GEN-END:variables
}
