/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Clases.Cl_Almacen;
import Vistas.frm_ver_empleados;
import Clases.Cl_Conectar;
import Clases.Cl_Empresa;
import Clases.Cl_Persona;
import Clases.Cl_Varios;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */
public class frm_reg_empleado extends javax.swing.JInternalFrame {

    Cl_Conectar con = new Cl_Conectar();
    Cl_Varios ven = new Cl_Varios();
    Cl_Persona per = new Cl_Persona();
    Cl_Empresa emp = new Cl_Empresa();
    Cl_Almacen alm = new Cl_Almacen();
    public static String accion = "registrar";

    /**
     * Creates new form frm_reg_empleado
     */
    public frm_reg_empleado() {
        initComponents();
        emp.ver_empresas(cbx_empresa);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_lim = new javax.swing.JButton();
        btn_reg = new javax.swing.JButton();
        btn_cer = new javax.swing.JButton();
        txt_tel = new javax.swing.JTextField();
        txt_dir = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_ndoc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_nom = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_jor = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_ape_pat = new javax.swing.JTextField();
        txt_ape_mat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbx_empresa = new javax.swing.JComboBox();
        cbx_tienda = new javax.swing.JComboBox();
        txt_empresa = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        txt_cargo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_fecha = new javax.swing.JFormattedTextField();

        setTitle("Registrar Empleado");

        btn_lim.setText("Limpiar");
        btn_lim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limActionPerformed(evt);
            }
        });

        btn_reg.setText("Registrar");
        btn_reg.setEnabled(false);
        btn_reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regActionPerformed(evt);
            }
        });

        btn_cer.setText("Cerrar");
        btn_cer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerActionPerformed(evt);
            }
        });

        txt_tel.setEnabled(false);
        txt_tel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_telKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_telKeyTyped(evt);
            }
        });

        txt_dir.setEnabled(false);
        txt_dir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_dirKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_dirKeyTyped(evt);
            }
        });

        jLabel5.setText("Telefono:");

        txt_ndoc.setEnabled(false);
        txt_ndoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_ndocKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ndocKeyTyped(evt);
            }
        });

        jLabel3.setText("Nombres:");

        txt_nom.setEnabled(false);
        txt_nom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_nomKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nomKeyTyped(evt);
            }
        });

        jLabel4.setText("Direccion:");

        jLabel2.setText("DNI.");

        jLabel1.setText("Mensual:");

        txt_jor.setEnabled(false);
        txt_jor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_jorKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_jorKeyTyped(evt);
            }
        });

        jLabel8.setText("Apellido Paterno:");

        jLabel9.setText("Apellido Materno:");

        txt_ape_pat.setEnabled(false);
        txt_ape_pat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_ape_patKeyPressed(evt);
            }
        });

        txt_ape_mat.setEnabled(false);
        txt_ape_mat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_ape_matKeyPressed(evt);
            }
        });

        jLabel6.setText("Empresa");

        jLabel7.setText("Tienda");

        cbx_empresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbx_empresaKeyPressed(evt);
            }
        });

        cbx_tienda.setEnabled(false);
        cbx_tienda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbx_tiendaKeyPressed(evt);
            }
        });

        txt_empresa.setFocusable(false);

        jLabel10.setText("email:");

        jLabel11.setText("Contraseña:");

        txt_email.setEnabled(false);
        txt_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_emailKeyPressed(evt);
            }
        });

        txt_password.setEnabled(false);
        txt_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_passwordKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_passwordKeyTyped(evt);
            }
        });

        jLabel12.setText("Cargo:");

        txt_cargo.setEnabled(false);
        txt_cargo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_cargoKeyPressed(evt);
            }
        });

        jLabel13.setText("Fecha Nacimiento:");

        try {
            txt_fecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_fecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_fecha.setToolTipText("");
        txt_fecha.setEnabled(false);
        txt_fecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_fechaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_lim)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_empresa)
                            .addComponent(txt_ndoc, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_nom, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btn_reg)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_cer))
                            .addComponent(txt_dir)
                            .addComponent(txt_jor, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ape_pat)
                            .addComponent(txt_ape_mat)
                            .addComponent(cbx_empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbx_tienda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_email)
                            .addComponent(txt_tel, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_cargo, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_empresa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_empresa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_tienda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ndoc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ape_pat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ape_mat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cargo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txt_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_dir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_jor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_lim, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_reg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_limActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limActionPerformed
        txt_ndoc.setText("");
        txt_nom.setText("");
        txt_dir.setText("");
        txt_tel.setText("");
        txt_ndoc.requestFocus();
    }//GEN-LAST:event_btn_limActionPerformed

    private void llenar() {
        per.setEmpresa(cbx_empresa.getSelectedItem().toString().trim());
        per.setTienda(cbx_tienda.getSelectedIndex() + 1);
        per.setNro_doc(txt_ndoc.getText());
        per.setNom_per(txt_nom.getText().toUpperCase());
        per.setApe_pat(txt_ape_pat.getText().toUpperCase());
        per.setApe_mat(txt_ape_mat.getText().toUpperCase());
        per.setDir_per(txt_dir.getText().toUpperCase());
        per.setTel_per(Integer.parseInt(txt_tel.getText()));
        per.setEmail(txt_email.getText().toLowerCase());
        per.setContrasena(txt_password.getText().toLowerCase().trim());
        per.setDiario(Double.parseDouble(txt_jor.getText()));
        per.setCargo(txt_cargo.getText().toUpperCase().trim());
        per.setFecha_nacimiento(ven.fechabase(txt_fecha.getText()));
        per.setEst_per("1");
    }
    private void btn_regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regActionPerformed
        llenar();
        if (accion.equals("registrar")) {
            try {
                Statement st = con.conexion();
                String insert_per = "insert into empleados Values ('" + per.getNro_doc() + "', '" + per.getEmpresa() + "', '" + per.getTienda() + "', '" + per.getNom_per() + "', '" + per.getApe_pat() + "', '" + per.getApe_mat() + "', '" + per.getCargo()+ "',  '" + per.getDir_per() + "', '" + per.getTel_per() + "', "
                        + "'" + per.getFecha_nacimiento()+ "', '" + per.getDiario() + "', '" + per.getEmail() + "', '" + per.getContrasena() + "', '" + per.getEst_per() + "')";
                con.actualiza(st, insert_per);
                con.cerrar(st);
            } catch (Exception e) {
                System.out.println(e.getLocalizedMessage());
            }
            JOptionPane.showMessageDialog(null, "Se ha ingresado los datos");
        }
        if (accion.equals("modificar")) {
            try {
                Statement st = con.conexion();
                String insert_per = "update empleados set nombres = '" + per.getNom_per() + "', ape_pat = '" + per.getApe_pat() + "', ape_mat = '" + per.getApe_mat() + "', direccion = '" + per.getDir_per() + "', telefono = '" + per.getTel_per() + "', "
                        + "diario = '" + per.getDiario() + "' where dni = '" + per.getNro_doc() + "'";
                con.actualiza(st, insert_per);
                con.cerrar(st);
            } catch (Exception e) {
                System.out.println(e.getLocalizedMessage());
            }
            JOptionPane.showMessageDialog(null, "Se ha modificado los datos");
        }
        frm_ver_empleados empleado = new frm_ver_empleados();
        ven.llamar_ventana(empleado);
        accion = "";
        this.dispose();
    }//GEN-LAST:event_btn_regActionPerformed

    private void btn_cerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerActionPerformed
        frm_ver_empleados empleado = new frm_ver_empleados();
        ven.llamar_ventana(empleado);
        accion = "";
        this.dispose();
    }//GEN-LAST:event_btn_cerActionPerformed

    private void txt_ndocKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ndocKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                per.setNro_doc(txt_ndoc.getText());
                Statement st = con.conexion();
                String buscar = "select * from empleados where dni = '" + per.getNro_doc() + "'";
                ResultSet rs = con.consulta(st, buscar);
                if (rs.next()) {
                    JOptionPane.showMessageDialog(null, "El empleado ya existe, ingrese otro dni");
                    txt_ndoc.setText("");
                    txt_ndoc.requestFocus();
                } else {
                    txt_nom.setEnabled(true);
                    txt_nom.requestFocus();
                }
            } catch (SQLException ex) {
                System.out.print(ex);
            }
        }
    }//GEN-LAST:event_txt_ndocKeyPressed

    private void txt_nomKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nomKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!txt_nom.getText().isEmpty()) {
                txt_ape_pat.setEnabled(true);
                txt_ape_pat.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_nomKeyPressed

    private void txt_dirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_dirKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!txt_dir.getText().isEmpty()) {
                txt_tel.setEnabled(true);
                txt_tel.requestFocus();
            }

        }
    }//GEN-LAST:event_txt_dirKeyPressed

    private void txt_telKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_telKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!txt_tel.getText().isEmpty()) {
                txt_jor.setEnabled(true);
                txt_jor.requestFocus();
            }

        }
    }//GEN-LAST:event_txt_telKeyPressed

    private void txt_ndocKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ndocKeyTyped
        ven.limitar_caracteres(evt, txt_ndoc, 8);
        ven.solo_numeros(evt);
    }//GEN-LAST:event_txt_ndocKeyTyped

    private void txt_nomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nomKeyTyped
        if (txt_nom.getText().length() == 245) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_nomKeyTyped

    private void txt_dirKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_dirKeyTyped
        if (txt_dir.getText().length() == 245) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_dirKeyTyped

    private void txt_telKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_telKeyTyped
        ven.solo_numeros(evt);
    }//GEN-LAST:event_txt_telKeyTyped

    private void txt_jorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_jorKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!txt_jor.getText().isEmpty()) {
                txt_email.setEnabled(true);
                txt_email.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_jorKeyPressed

    private void txt_jorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_jorKeyTyped
        ven.solo_precio(evt);
        ven.limitar_caracteres(evt, txt_jor, 8);
    }//GEN-LAST:event_txt_jorKeyTyped

    private void txt_ape_patKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ape_patKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!txt_ape_pat.getText().isEmpty()) {
                txt_ape_mat.setEnabled(true);
                txt_ape_mat.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_ape_patKeyPressed

    private void txt_ape_matKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ape_matKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!txt_ape_mat.getText().isEmpty()) {
                txt_cargo.setEnabled(true);
                txt_cargo.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_ape_matKeyPressed

    private void cbx_empresaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbx_empresaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            emp.setRuc(cbx_empresa.getSelectedItem().toString());
            txt_empresa.setText(emp.obtener_razon());
            cbx_tienda.setEnabled(true);
            alm.ver_tiendas_empresa(cbx_tienda, emp.getRuc());
            cbx_tienda.requestFocus();
        }
    }//GEN-LAST:event_cbx_empresaKeyPressed

    private void cbx_tiendaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbx_tiendaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            alm.setCodigo(cbx_tienda.getSelectedIndex() + 1);
            txt_ndoc.setEnabled(true);
            txt_ndoc.requestFocus();
        }
    }//GEN-LAST:event_cbx_tiendaKeyPressed

    private void txt_passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passwordKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!txt_password.getText().isEmpty()) {
                btn_reg.setEnabled(true);
                btn_reg.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_passwordKeyPressed

    private void txt_passwordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passwordKeyTyped
        ven.limitar_caracteres(evt, txt_password, 15);
    }//GEN-LAST:event_txt_passwordKeyTyped

    private void txt_emailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_emailKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!txt_email.getText().isEmpty()) {
                txt_password.setEnabled(true);
                txt_password.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_emailKeyPressed

    private void txt_cargoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cargoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!txt_cargo.getText().isEmpty()) {
                txt_fecha.setEnabled(true);
                txt_fecha.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_cargoKeyPressed

    private void txt_fechaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_fechaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txt_fecha.getText().length()==10) {
                txt_dir.setEnabled(true);
                txt_dir.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_fechaKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cer;
    private javax.swing.JButton btn_lim;
    private javax.swing.JButton btn_reg;
    private javax.swing.JComboBox cbx_empresa;
    private javax.swing.JComboBox cbx_tienda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JTextField txt_ape_mat;
    public static javax.swing.JTextField txt_ape_pat;
    private javax.swing.JTextField txt_cargo;
    public static javax.swing.JTextField txt_dir;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_empresa;
    private javax.swing.JFormattedTextField txt_fecha;
    public static javax.swing.JTextField txt_jor;
    public static javax.swing.JTextField txt_ndoc;
    public static javax.swing.JTextField txt_nom;
    private javax.swing.JPasswordField txt_password;
    public static javax.swing.JTextField txt_tel;
    // End of variables declaration//GEN-END:variables
}
