/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Vistas.frm_ver_compras;
import Clases.Cl_Compra;
import Clases.Cl_Conectar;
import Clases.Cl_Empresa;
import Clases.Cl_Proveedor;
import Clases.Cl_Tipo_Doc;
import Clases.Cl_Varios;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import com.mxrck.autocompleter.AutoCompleterCallback;
import com.mxrck.autocompleter.TextAutoCompleter;

/**
 *
 * @author CONTABILIDAD 02
 */
public class frm_reg_compra extends javax.swing.JInternalFrame {

    Cl_Varios ven = new Cl_Varios();
    Cl_Conectar con = new Cl_Conectar();
    Cl_Proveedor pro = new Cl_Proveedor();
    Cl_Tipo_Doc tido = new Cl_Tipo_Doc();
    Cl_Compra com = new Cl_Compra();
    Cl_Empresa emp = new Cl_Empresa();
    Double monto, tc_compra;
    int idmon;
    String periodo, glosa;
    public static String accion;

    /**
     * Creates new form frm_reg_compra
     */
    public frm_reg_compra() {
        initComponents();
        String ver_tido = "select nombre from tipo_documento";
        ver_tipodoc(ver_tido);

        String ver_mon = "select nombre from moneda order by id_moneda asc";
        ver_moneda(ver_mon);

        cargar_proveedores();
        emp.ver_empresas(cbx_empresas);
    }

    private void ver_tipodoc(String query) {
        try {
            Statement st = con.conexion();
            ResultSet rs = con.consulta(st, query);

            while (rs.next()) {
                String fila;
                fila = rs.getString("nombre");
                cbx_tido.addItem(fila);
            }
            con.cerrar(st);
            con.cerrar(rs);
        } catch (SQLException e) {
            System.out.print(e);
        }
    }

    private void ver_moneda(String query) {
        try {
            Statement st = con.conexion();
            ResultSet rs = con.consulta(st, query);

            while (rs.next()) {
                String fila;
                fila = rs.getString("nombre");
                cbx_mon.addItem(fila);
            }
            con.cerrar(st);
            con.cerrar(rs);
        } catch (SQLException e) {
            System.out.print(e);
        }
    }

    private Integer ver_cod(String periodo, String empresa) {
        Integer cod_com = 0;
        try {
            Statement st = con.conexion();
            String ver_cod_per = "select id_compra from compras where periodo = '" + periodo + "' and empresa = '" + empresa + "' order by id_compra desc limit 1";
            ResultSet rs = con.consulta(st, ver_cod_per);
            if (rs.next()) {
                cod_com = rs.getInt("id_compra");
            } else {
                cod_com = 0;
            }
            con.cerrar(rs);
            con.cerrar(st);
        } catch (SQLException e) {
            System.out.println(e.getLocalizedMessage());
        }
        cod_com = cod_com + 1;
        return cod_com;
    }

    private void cargar_proveedores() {
        try {
            // autocompletar = new TextAutoCompleter(txt_buscar_producto);
            TextAutoCompleter autocompletar = new TextAutoCompleter(txt_ruc, new AutoCompleterCallback() {
                @Override
                public void callback(Object selectedItem) {
                    txt_ruc.setText("");
                    txt_ruc.requestFocus();
                    String cadena = selectedItem.toString();
                    JOptionPane.showMessageDialog(null, "El usuario seleccionó: " + cadena);
                }
            });

            autocompletar.setMode(0);
            autocompletar.setCaseSensitive(false);
            Statement st = con.conexion();
            String sql = "select ruc_proveedor from proveedores order by ruc_proveedor asc";
            ResultSet rs = con.consulta(st, sql);
            while (rs.next()) {
                autocompletar.addItem(rs.getString("ruc_proveedor"));
            }
            con.cerrar(rs);
            con.cerrar(st);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error " + e.getLocalizedMessage());
            System.out.println(e.getLocalizedMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_fec_com = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        txt_sub = new javax.swing.JTextField();
        txt_per = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_ndoc = new javax.swing.JTextField();
        cbx_mon = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_tica = new javax.swing.JTextField();
        txt_ruc = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_ser = new javax.swing.JTextField();
        cbx_tido = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        txt_raz = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_igv = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_tot = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_glosa = new javax.swing.JTextField();
        btn_reg = new javax.swing.JButton();
        btn_cer = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txt_empresas = new javax.swing.JTextField();
        cbx_empresas = new javax.swing.JComboBox();
        cbx_afecto = new javax.swing.JCheckBox();

        setTitle("Registro de Documento de Compra");

        try {
            txt_fec_com.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_fec_com.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_fec_com.setEnabled(false);
        txt_fec_com.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_fec_comKeyPressed(evt);
            }
        });

        jLabel3.setText("Tipo Doc.");

        txt_id.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_id.setEnabled(false);

        txt_sub.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_sub.setEnabled(false);
        txt_sub.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_subKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_subKeyTyped(evt);
            }
        });

        try {
            txt_per.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_per.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_per.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_perKeyPressed(evt);
            }
        });

        jLabel11.setText("Periodo:");

        txt_ndoc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_ndoc.setEnabled(false);
        txt_ndoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_ndocKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ndocKeyTyped(evt);
            }
        });

        cbx_mon.setEnabled(false);
        cbx_mon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbx_monKeyPressed(evt);
            }
        });

        jLabel1.setText("Proveedor:");

        jLabel6.setText("Moneda:");

        jLabel5.setText("Nro. Doc:");

        txt_tica.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_tica.setEnabled(false);
        txt_tica.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_ticaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ticaKeyTyped(evt);
            }
        });

        txt_ruc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_ruc.setEnabled(false);
        txt_ruc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_rucKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_rucKeyTyped(evt);
            }
        });

        jLabel10.setText("T.C.");

        txt_ser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_ser.setEnabled(false);
        txt_ser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_serKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_serKeyTyped(evt);
            }
        });

        cbx_tido.setEnabled(false);
        cbx_tido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbx_tidoKeyPressed(evt);
            }
        });

        jLabel4.setText("Serie:");

        txt_raz.setEnabled(false);

        jLabel2.setText("Fecha:");

        jLabel7.setText("Sub Total:");

        jLabel8.setText("IGV");

        txt_igv.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_igv.setEnabled(false);
        txt_igv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_igvKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_igvKeyTyped(evt);
            }
        });

        jLabel9.setText("Total:");

        txt_tot.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_tot.setEnabled(false);

        jLabel12.setText("Glosa:");

        txt_glosa.setEnabled(false);
        txt_glosa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_glosaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_glosaKeyTyped(evt);
            }
        });

        btn_reg.setText("Registrar");
        btn_reg.setEnabled(false);
        btn_reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regActionPerformed(evt);
            }
        });

        btn_cer.setText("Cerrar");
        btn_cer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerActionPerformed(evt);
            }
        });

        jLabel13.setText("Empresa:");

        txt_empresas.setEnabled(false);

        cbx_empresas.setEnabled(false);
        cbx_empresas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbx_empresasKeyPressed(evt);
            }
        });

        cbx_afecto.setText("Inafecto IGV");
        cbx_afecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_afectoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(24, 24, 24)
                        .addComponent(txt_glosa))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_reg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_cer))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbx_tido, 0, 150, Short.MAX_VALUE)
                            .addComponent(txt_ser, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(txt_ndoc, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(txt_per, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbx_empresas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_sub, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_igv, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txt_fec_com, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txt_ruc, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txt_raz))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel9)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(cbx_mon, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(25, 25, 25)
                                                        .addComponent(jLabel10)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(txt_tica, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(txt_tot, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(0, 0, Short.MAX_VALUE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addGap(0, 60, Short.MAX_VALUE)
                                                        .addComponent(cbx_afecto))))))))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_empresas)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_per, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_fec_com, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_empresas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbx_empresas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbx_tido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ruc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_raz, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(cbx_mon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_tica, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbx_afecto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(txt_sub, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_igv, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_tot, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ndoc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_glosa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_reg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_cer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_fec_comKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_fec_comKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txt_fec_com.getText().length() == 10) {
                String empresa = cbx_empresas.getSelectedItem().toString();
                //capturar mes y año de fecha ingresada
                String fec_com = txt_fec_com.getText();
                String mes_fec = fec_com.charAt(3) + "" + fec_com.charAt(4);
                String anio_fec = fec_com.charAt(6) + "" + fec_com.charAt(7) + "" + fec_com.charAt(8) + "" + fec_com.charAt(9);
                //separar mes y año de periodo
                String per_txt = txt_per.getText();
                String mes_per = per_txt.charAt(0) + "" + per_txt.charAt(1);
                String anio_per = per_txt.charAt(3) + "" + per_txt.charAt(4) + "" + per_txt.charAt(5) + "" + per_txt.charAt(6);
                //comparar fecha y periodo
                if (Integer.parseInt(anio_fec) <= Integer.parseInt(anio_per)) {
                    txt_ruc.setEnabled(true);
                    txt_ruc.requestFocus();
                    txt_id.setText("" + ver_cod(per_txt, empresa));
                } else if (Double.parseDouble(mes_fec) <= Double.parseDouble(mes_per)) {
                    txt_ruc.setEnabled(true);
                    txt_ruc.requestFocus();
                    txt_id.setText("" + ver_cod(per_txt, empresa));
                } else {
                    JOptionPane.showMessageDialog(null, "Fecha no valida en el periodo");
                }

            }
        }
    }//GEN-LAST:event_txt_fec_comKeyPressed

    private void txt_subKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_subKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String texto = txt_sub.getText();
            if (texto.length() > 0) {
                if (ven.esDecimal(texto)) {
                    Double base = Double.parseDouble(txt_sub.getText());
                    double igv;
                    double total;
                    if (!cbx_afecto.isSelected()) {
                        igv = base * 0.18;
                        total = base * 1.18;
                    } else {
                        igv = 0;
                        total = base;
                    }
                    txt_igv.setText(ven.formato_numero(igv));
                    txt_tot.setText(ven.formato_numero(total));
                    txt_igv.setEnabled(true);
                    txt_igv.requestFocus();
                } else {
                    txt_sub.setText("");
                    txt_sub.requestFocus();
                }
            }
        }
    }//GEN-LAST:event_txt_subKeyPressed

    private void txt_perKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_perKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txt_per.getText().length() == 7) {
                cbx_empresas.setEnabled(true);
                cbx_empresas.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_perKeyPressed

    private void txt_ndocKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ndocKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!txt_ndoc.getText().isEmpty()) {
                txt_fec_com.setEnabled(true);
                txt_fec_com.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_ndocKeyPressed

    private Double tc_compra(String fecha) {
        double tc = 0.0;
        try {
            Statement st = con.conexion();
            String ver_tc = "select compra from tipo_cambio where fecha = '" + fecha + "'";
            System.out.println(ver_tc);
            ResultSet rs = con.consulta(st, ver_tc);
            if (rs.next()) {
                tc = rs.getDouble("compra");
            } else {
                tc = 0.0;
            }
            con.cerrar(rs);
            con.cerrar(st);
        } catch (Exception e) {
            System.out.println(e.getLocalizedMessage());
        }
        return tc;
    }

    private void cbx_monKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbx_monKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (cbx_mon.getSelectedIndex() == 0) {
                txt_tica.setText("1.000");
            }
            //txt_tica.setText(tc_compra(ven.fechabase(txt_fec_com.getText())).toString());
            txt_tica.setEnabled(true);
            txt_tica.selectAll();
            txt_tica.requestFocus();
        }
    }//GEN-LAST:event_cbx_monKeyPressed

    private void txt_ticaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ticaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txt_tica.getText().length() > 3) {
                cbx_afecto.setEnabled(true);
                txt_sub.setEnabled(true);
                txt_sub.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_ticaKeyPressed

    private boolean comprobar_doc(String ruc, String ser, int nro, int idtido) {
        boolean existe = false;
        try {
            Statement st = con.conexion();
            String ver_doc = "select id_compra, periodo from compras where ruc_proveedor = '" + ruc + "' and serie = '" + ser + "' and numero = '" + nro + "' and id_tido = '" + idtido + "'";
            System.out.println(ver_doc);
            ResultSet rs = con.consulta(st, ver_doc);
            if (rs.next()) {
                existe = true;
                System.out.println(rs.getInt("id_compra") + "-" + rs.getString("periodo"));
            }
        } catch (Exception e) {
            System.out.println(e.getLocalizedMessage());
        }
        return existe;
    }

    private void txt_rucKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_rucKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txt_ruc.getText().length() == 11) {
                pro.setRuc(txt_ruc.getText());
                boolean ruc_valido = pro.validar_RUC(pro.getRuc());
                if (ruc_valido == true) {
                    try {
                        Statement st = con.conexion();
                        String ver_pro = "select razon_social from proveedores where ruc_proveedor = '" + pro.getRuc() + "'";
                        ResultSet rs = con.consulta(st, ver_pro);
                        if (rs.next()) {
                            boolean comprueba_doc = comprobar_doc(pro.getRuc(), txt_ser.getText(), Integer.parseInt(txt_ndoc.getText()), cbx_tido.getSelectedIndex() + 1);
                            if (comprueba_doc == false) {
                                pro.setRaz_soc(rs.getString("razon_social"));
                                txt_raz.setText(rs.getString("razon_social"));
                                cbx_mon.setEnabled(true);
                                cbx_mon.requestFocus();
                            } else {
                                txt_ruc.setText("");
                                txt_ruc.requestFocus();
                                JOptionPane.showMessageDialog(null, "El Documento ya existe");
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "El Proveedor no existe");
                            frm_reg_proveedor proveedor = new frm_reg_proveedor();
                            frm_reg_proveedor.origen = "compra";
                            frm_reg_proveedor.accion = "registrar";
                            ven.llamar_ventana(proveedor);
                        }
                    } catch (SQLException ex) {
                        System.out.print(ex);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "EL RUC INGRESADO NO ES VALIDO \nVERIFIQUE POR FAVOR");
                }
            } else {
                JOptionPane.showMessageDialog(null, "FALTAN DIGITOS AL NUMERO DE RUC");
            }
        }
    }//GEN-LAST:event_txt_rucKeyPressed

    private void txt_rucKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_rucKeyTyped
        if (txt_ruc.getText().length() == 11) {
            evt.consume();
        }
        char car = evt.getKeyChar();
        if ((car < '0' || car > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_rucKeyTyped

    private void txt_serKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_serKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!txt_ser.getText().isEmpty()) {
                txt_ndoc.setEnabled(true);
                txt_ndoc.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_serKeyPressed

    private void cbx_tidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbx_tidoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txt_ser.setEnabled(true);
            txt_ser.requestFocus();
        }
    }//GEN-LAST:event_cbx_tidoKeyPressed

    private void txt_serKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_serKeyTyped
        if (txt_ser.getText().length() == 12) {
            evt.consume();
        }

        char car = evt.getKeyChar();
        if ((car < '0' || car > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_serKeyTyped

    private void txt_glosaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_glosaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txt_glosa.getText().length() > 5) {
                btn_reg.setEnabled(true);
                btn_reg.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_glosaKeyPressed

    private void llenar() {
        com.setId(Integer.parseInt(txt_id.getText()));
        com.setNumero(txt_ndoc.getText());
        com.setSerie(txt_ser.getText());
        com.setFecha_compra(ven.fechabase(txt_fec_com.getText()));
        pro.setRuc(txt_ruc.getText());
        tido.setId(cbx_tido.getSelectedIndex() + 1);
        idmon = cbx_mon.getSelectedIndex() + 1;
        com.setEstado("0");
        monto = Double.parseDouble(txt_sub.getText());
        tc_compra = Double.parseDouble(txt_tica.getText());
        periodo = txt_per.getText();
        glosa = txt_glosa.getText().toUpperCase();
        emp.setRuc(cbx_empresas.getSelectedItem().toString());
    }

    private void btn_regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regActionPerformed
        llenar();
        double igv = Double.parseDouble(txt_igv.getText());
        String afecto = "1";
        if (cbx_afecto.isSelected()) {
            afecto = "0";
        }
        if (accion.equals("registrar")) {
            Statement st = con.conexion();
            String ins_com = "insert into compras values ('" + com.getId() + "', '" + periodo + "', '" + emp.getRuc() + "','" + pro.getRuc() + "', '" + tido.getId() + "', "
                    + "'" + com.getSerie() + "', '" + com.getNumero() + "','" + com.getFecha_compra() + "',  '7000-01-01', '" + idmon + "', '" + tc_compra + "',  '" + monto + "', "
                    + "'" + igv + "', '" + afecto + "','" + com.getEstado() + "', '" + glosa + "', NOW())";
            System.out.println(ins_com);
            con.actualiza(st, ins_com);
            con.cerrar(st);
        }
        if (accion.equals("modificar")) {
            Statement st = con.conexion();
            String ins_com = "update compras set ruc_proveedor = '" + pro.getRuc() + "', id_tido = '" + tido.getId() + "', serie = '" + com.getSerie() + "', numero = '" + com.getNumero() + "', "
                    + "fecha_compra = '" + com.getFecha_compra() + "', id_moneda =  '" + idmon + "', tc_compra = '" + tc_compra + "',  sub_total = '" + monto + "', igv = '" + igv + "', "
                    + "afecto = '" + afecto + "', glosa = '" + glosa + "', fecha_registro = NOW() where id_compra = '" + com.getId() + "' and periodo = '" + periodo + "' and empresa = '" + emp.getRuc() + "' ";
            System.out.println(ins_com);
            con.actualiza(st, ins_com);
            con.cerrar(st);
        }
        accion = "";
        frm_ver_compras compra = new frm_ver_compras();
        ven.llamar_ventana(compra);
        this.dispose();
    }//GEN-LAST:event_btn_regActionPerformed

    private void txt_subKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_subKeyTyped
        ven.solo_precio(evt);
    }//GEN-LAST:event_txt_subKeyTyped

    private void btn_cerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerActionPerformed
        frm_ver_compras compra = new frm_ver_compras();
        ven.llamar_ventana(compra);
        this.dispose();
    }//GEN-LAST:event_btn_cerActionPerformed

    private void txt_glosaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_glosaKeyTyped
        if (txt_glosa.getText().length() == 245) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_glosaKeyTyped

    private void txt_ticaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ticaKeyTyped
        char car = evt.getKeyChar();
        if ((car < '0' || car > '9') && car != '.') {
            evt.consume();
        }
    }//GEN-LAST:event_txt_ticaKeyTyped

    private void txt_ndocKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ndocKeyTyped
        if (txt_ndoc.getText().length() == 20) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_ndocKeyTyped

    private void cbx_empresasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbx_empresasKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            emp.setRuc(cbx_empresas.getSelectedItem().toString());
            txt_empresas.setText(emp.obtener_razon());
            cbx_tido.setEnabled(true);
            cbx_tido.requestFocus();
        }
    }//GEN-LAST:event_cbx_empresasKeyPressed

    private void txt_igvKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_igvKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String texto = txt_igv.getText();
            if (texto.length() > 0) {
                if (ven.esDecimal(texto)) {
                    Double igv = Double.parseDouble(txt_igv.getText());
                    Double base = Double.parseDouble(txt_sub.getText());
                    double total;
                    if (!cbx_afecto.isSelected()) {
                        total = base + igv;
                    } else {
                        total = base;
                        igv = 0.0;
                    }
                    txt_igv.setText(ven.formato_numero(igv));
                    txt_tot.setText(ven.formato_numero(total));
                    txt_glosa.setEnabled(true);
                    txt_glosa.requestFocus();
                } else {
                    txt_igv.setText("0.00");
                    txt_igv.requestFocus();
                }
            }
        }
    }//GEN-LAST:event_txt_igvKeyPressed

    private void txt_igvKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_igvKeyTyped
        ven.solo_precio(evt);
    }//GEN-LAST:event_txt_igvKeyTyped

    private void cbx_afectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_afectoActionPerformed
        txt_sub.requestFocus();
    }//GEN-LAST:event_cbx_afectoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cer;
    public static javax.swing.JButton btn_reg;
    public static javax.swing.JCheckBox cbx_afecto;
    public static javax.swing.JComboBox cbx_empresas;
    public static javax.swing.JComboBox cbx_mon;
    public static javax.swing.JComboBox cbx_tido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JTextField txt_empresas;
    public static javax.swing.JFormattedTextField txt_fec_com;
    public static javax.swing.JTextField txt_glosa;
    public static javax.swing.JTextField txt_id;
    public static javax.swing.JTextField txt_igv;
    public static javax.swing.JTextField txt_ndoc;
    public static javax.swing.JFormattedTextField txt_per;
    public static javax.swing.JTextField txt_raz;
    public static javax.swing.JTextField txt_ruc;
    public static javax.swing.JTextField txt_ser;
    public static javax.swing.JTextField txt_sub;
    public static javax.swing.JTextField txt_tica;
    public static javax.swing.JTextField txt_tot;
    // End of variables declaration//GEN-END:variables
}
