/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Vistas.frm_ver_clientes;
import Clases.Cl_Persona;
import Clases.Cl_Conectar;
import Clases.Cl_Varios;
import com.mxrck.autocompleter.TextAutoCompleter;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */
public class frm_reg_cliente extends javax.swing.JInternalFrame {

    Cl_Varios ven = new Cl_Varios();
    Cl_Conectar con = new Cl_Conectar();
    Cl_Persona cli = new Cl_Persona();
    public static String accion = "";
    public static String origen = "";

    /**
     * Creates new form frm_reg_cliente
     */
    public frm_reg_cliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbx_cli = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        txt_ndoc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_nom = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_dir = new javax.swing.JTextField();
        txt_tel = new javax.swing.JTextField();
        btn_cer = new javax.swing.JButton();
        btn_reg = new javax.swing.JButton();
        btn_lim = new javax.swing.JButton();
        lbl_codigo = new javax.swing.JLabel();

        setTitle("Registrar Cliente");

        jLabel1.setText("Tipo de Documento");

        cbx_cli.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DNI", "RUC" }));
        cbx_cli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbx_cliKeyPressed(evt);
            }
        });

        jLabel2.setText("Nro de Doc:");

        txt_ndoc.setEnabled(false);
        txt_ndoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_ndocKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ndocKeyTyped(evt);
            }
        });

        jLabel3.setText("Nombre o Razon Social:");

        txt_nom.setEnabled(false);
        txt_nom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_nomKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nomKeyTyped(evt);
            }
        });

        jLabel4.setText("Direccion:");

        jLabel5.setText("Telefono:");

        txt_dir.setEnabled(false);
        txt_dir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_dirKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_dirKeyTyped(evt);
            }
        });

        txt_tel.setEnabled(false);
        txt_tel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_telKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_telKeyTyped(evt);
            }
        });

        btn_cer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/cancel.png"))); // NOI18N
        btn_cer.setText("Cerrar");
        btn_cer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerActionPerformed(evt);
            }
        });

        btn_reg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/add.png"))); // NOI18N
        btn_reg.setText("Registrar");
        btn_reg.setEnabled(false);
        btn_reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regActionPerformed(evt);
            }
        });
        btn_reg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_regKeyPressed(evt);
            }
        });

        btn_lim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/asterisk_orange.png"))); // NOI18N
        btn_lim.setText("Limpiar");
        btn_lim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limActionPerformed(evt);
            }
        });

        lbl_codigo.setText("codigo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_lim)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbx_cli, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_codigo))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btn_reg)
                                .addGap(26, 26, 26)
                                .addComponent(btn_cer))
                            .addComponent(txt_dir, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                            .addComponent(txt_nom)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_tel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_ndoc, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(25, 25, 25))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_cli, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_codigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ndoc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_dir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_lim, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_reg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerActionPerformed
        if (origen.equals("cliente")) {
            frm_ver_clientes cliente = new Vistas.frm_ver_clientes();
            ven.llamar_ventana(cliente);
        }

        accion = "";
        origen = "";
        this.dispose();
    }//GEN-LAST:event_btn_cerActionPerformed

    private void llenar() {
        cli.setNom_per(txt_nom.getText().toUpperCase().trim());
        cli.setNro_doc(txt_ndoc.getText());
        cli.setDir_per(txt_dir.getText().toUpperCase().trim());
        cli.setTel_per(Integer.parseInt(txt_tel.getText().trim()));
    }
    private void btn_regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regActionPerformed
        llenar();

        if (accion.equals("registrar")) {
            try {
                Statement st = con.conexion();
                String inser_cli = "insert into clientes Values (null, '" + cli.getNro_doc() + "', '" + cli.getNom_per() + "', '" + cli.getDir_per() + "', '" + cli.getTel_per() + "')";
                con.actualiza(st, inser_cli);
                con.cerrar(st);
                //btn_cer.doClick();
            } catch (Exception e) {
                System.out.println(e);
                JOptionPane.showMessageDialog(null, e.getLocalizedMessage());
            }

        }

        if (accion.equals("mod")) {
            Statement st = con.conexion();
            String act_cli = "update clientes set nro_documento = '" + cli.getNro_doc() + "', nombre =  '" + cli.getNom_per() + "', direccion = '" + cli.getDir_per() + "', telefono = '" + cli.getTel_per() + "' "
                    + "where id = '" + lbl_codigo.getText() + "'";
            con.actualiza(st, act_cli);
            con.cerrar(st);
            JOptionPane.showMessageDialog(null, "Se ha modificado los datos");
            btn_cer.doClick();
        }

        if (origen.equals("cliente")) {
            frm_ver_clientes cliente = new Vistas.frm_ver_clientes();
            ven.llamar_ventana(cliente);
        }

        accion = "";
        origen = "";
        this.dispose();
    }//GEN-LAST:event_btn_regActionPerformed

    private void btn_limActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limActionPerformed
        cbx_cli.setSelectedIndex(0);
        txt_ndoc.setText("");
        txt_nom.setText("");
        txt_dir.setText("");
        txt_tel.setText("");
        txt_ndoc.setEnabled(false);
        txt_nom.setEnabled(false);
        txt_dir.setEnabled(false);
        txt_tel.setEnabled(false);
        btn_reg.setEnabled(false);
        cbx_cli.requestFocus();
    }//GEN-LAST:event_btn_limActionPerformed

    private void txt_ndocKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ndocKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            boolean ingreso_valido = false;
            if (cbx_cli.getSelectedItem().equals("DNI")) {
                if (txt_ndoc.getText().length() == 8) {
                    try {
                        cli.setNro_doc(txt_ndoc.getText());
                        Statement st = con.conexion();
                        String buscar = "select * from clientes where nro_documento = '" + cli.getNro_doc() + "'";
                        ResultSet rs = con.consulta(st, buscar);
                        if (rs.next()) {
                            JOptionPane.showMessageDialog(null, "El cliente ya existe, ingrese otro numero");
                            txt_ndoc.setText("");
                            txt_ndoc.requestFocus();
                        } else {
                            ingreso_valido = true;
                        }
                    } catch (SQLException ex) {
                        System.out.print(ex);
                        JOptionPane.showMessageDialog(null, ex.getLocalizedMessage());
                    }
                }
                if (txt_ndoc.getText().length() == 0) {
                    ingreso_valido = true;
                    txt_ndoc.setEnabled(false);
                    cbx_cli.setEnabled(false);
                }
            }
            if (cbx_cli.getSelectedItem().equals("RUC") && txt_ndoc.getText().length() == 11) {
                try {
                    cli.setNro_doc(txt_ndoc.getText());
                    Statement st = con.conexion();
                    String buscar = "select * from clientes where nro_documento = '" + cli.getNro_doc() + "'";
                    ResultSet rs = con.consulta(st, buscar);
                    if (rs.next()) {
                        JOptionPane.showMessageDialog(null, "El cliente ya existe, ingrese otro numero");
                        txt_ndoc.setText("");
                        txt_ndoc.requestFocus();
                    } else {
                        ingreso_valido = true;
                    }
                } catch (SQLException ex) {
                    System.out.print(ex);
                    JOptionPane.showMessageDialog(null, ex.getLocalizedMessage());
                }
            }

            if (ingreso_valido = true) {
                try {
                    TextAutoCompleter autocopletar = new TextAutoCompleter(txt_nom);
                    autocopletar.setMode(0);
                    Statement st = con.conexion();
                    String sql = "select nombre from clientes order by nombre asc";
                    ResultSet rs = con.consulta(st, sql);
                    while (rs.next()) {
                        autocopletar.addItem(rs.getString("nombre"));
                    }
                    con.cerrar(rs);
                    con.cerrar(st);
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, "Error" + e.getLocalizedMessage());
                    System.out.println(e);
                }
                txt_nom.setEnabled(true);
                txt_nom.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "EL INGRESO NO ES VALIDO.");
            }
        }
    }//GEN-LAST:event_txt_ndocKeyPressed

    private void txt_nomKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nomKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txt_nom.getText().length() > 0) {
                try {
                    Statement st = con.conexion();
                    String valida_nombre = "select id_cliente from clientes where nro_documento = '" + cli.getNro_doc() + "' or nombre = '" + cli.getNom_per() + "'";
                    ResultSet rs = con.consulta(st, valida_nombre);
                    if (rs.next()) {
                        JOptionPane.showMessageDialog(null, "EL CLIENTE YA EXISTE");
                        btn_cer.doClick();
                    } else {
                        txt_dir.setEnabled(true);
                        txt_dir.requestFocus();
                    }
                    con.cerrar(rs);
                    con.cerrar(st);
                } catch (SQLException | HeadlessException e) {
                    System.out.println(e);
                    JOptionPane.showMessageDialog(null, e.getLocalizedMessage());
                }
            }
        }
    }//GEN-LAST:event_txt_nomKeyPressed

    private void txt_dirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_dirKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txt_dir.getText().length() > 0) {
                txt_tel.setEnabled(true);
                txt_tel.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_dirKeyPressed

    private void txt_telKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_telKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txt_tel.getText().length() > 0) {
                btn_reg.setEnabled(true);
                btn_reg.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_telKeyPressed

    private void btn_regKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_regKeyPressed

    }//GEN-LAST:event_btn_regKeyPressed

    private void txt_ndocKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ndocKeyTyped
        char car = evt.getKeyChar();
        if ((car < '0' || car > '9')) {
            evt.consume();
        }

        if (cbx_cli.getSelectedItem().equals("DNI")) {
            if (txt_ndoc.getText().length() == 8) {
                evt.consume();
            }
        }

        if (cbx_cli.getSelectedItem().equals("RUC")) {
            if (txt_ndoc.getText().length() == 11) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_txt_ndocKeyTyped

    private void txt_nomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nomKeyTyped
        if (txt_nom.getText().length() == 245) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_nomKeyTyped

    private void txt_dirKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_dirKeyTyped
        if (txt_dir.getText().length() == 245) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_dirKeyTyped

    private void txt_telKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_telKeyTyped
        if (txt_tel.getText().length() == 9) {
            evt.consume();
        }
        char car = evt.getKeyChar();
        if ((car < '0' || car > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_telKeyTyped

    private void cbx_cliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbx_cliKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txt_ndoc.setEnabled(true);
            txt_ndoc.requestFocus();
        }
    }//GEN-LAST:event_cbx_cliKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cer;
    public static javax.swing.JButton btn_lim;
    public static javax.swing.JButton btn_reg;
    public static javax.swing.JComboBox cbx_cli;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel lbl_codigo;
    public static javax.swing.JTextField txt_dir;
    public static javax.swing.JTextField txt_ndoc;
    public static javax.swing.JTextField txt_nom;
    public static javax.swing.JTextField txt_tel;
    // End of variables declaration//GEN-END:variables
}
